[project]
name = "python-project-52"
version = "0.1.0"
description = "Task Manager on Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django",
    "gunicorn",
    "python-dotenv",
    "dj-database-url",
    "psycopg[binary]",
    "django-bootstrap5>=23.1"
]
