# Generated by Django 5.2.3 on 2025-06-19 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
