# Generated by Django 5.2.3 on 2025-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_label_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
